export function installAppMenus(){
 const nav=document.getElementById('layout-controls');nav.setAttribute('aria-label','เมนูหลัก');
 const menus=[];
 const closeAll=()=>{for(const {button,popup} of menus){popup.hidden=true;button.setAttribute('aria-expanded','false');}};
 const add=(id,title,entries,before)=>{const wrapper=document.createElement('div');wrapper.className='app-menu';const button=document.createElement('button');button.id=id+'-menu-button';button.textContent=title+' ▾';button.setAttribute('aria-haspopup','menu');button.setAttribute('aria-expanded','false');const popup=document.createElement('div');popup.id=id+'-menu';popup.className='app-menu-popup';popup.setAttribute('role','menu');popup.setAttribute('aria-label',title);popup.hidden=true;button.setAttribute('aria-controls',popup.id);
 for(const entry of entries){let item;if(entry.target){item=document.getElementById(entry.target);if(!item)continue;}else{item=document.createElement('button');item.textContent=entry.label;item.onclick=entry.run;item.dataset.proxy='true';}item.setAttribute('role','menuitem');if(entry.label)item.textContent=entry.label;popup.append(item);}
 const available=()=>[...popup.querySelectorAll('button:not(:disabled)')];
 const open=(last=false)=>{closeAll();document.getElementById('view-menu').hidden=true;document.getElementById('view-menu-button').setAttribute('aria-expanded','false');const busy=document.getElementById('workspace').inert;for(const item of popup.querySelectorAll('button'))if(id==='rfi'||item.dataset.proxy)item.disabled=busy;popup.hidden=false;button.setAttribute('aria-expanded','true');(last?available().at(-1):available()[0])?.focus();};
 button.onclick=()=>popup.hidden?open():closeAll();button.onkeydown=e=>{if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();open(e.key==='ArrowUp');}};
 popup.addEventListener('click',e=>{if(e.target.closest('button')){const focus=popup.contains(document.activeElement);closeAll();if(focus)button.focus();}});
 popup.onkeydown=e=>{const items=available(),i=items.indexOf(document.activeElement);if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();items[e.key==='Home'?0:e.key==='End'?items.length-1:(i+(e.key==='ArrowDown'?1:-1)+items.length)%items.length]?.focus();}if(e.key==='Escape'){e.preventDefault();e.stopPropagation();closeAll();button.focus();}if(e.key==='Tab')closeAll();};wrapper.append(button,popup);if(before)nav.insertBefore(wrapper,before);else nav.append(wrapper);menus.push({button,popup});};
 add('file','ไฟล์',[{target:'new-project',label:'งานใหม่'},{target:'rename-project',label:'เปลี่ยนชื่องาน'},{target:'manage-projects',label:'จัดการงาน'},{label:'นำเข้าแบบ…',run:()=>document.getElementById('drawing-file-input').click()},{target:'save-state'},{target:'backup-project'},{target:'restore-project'}],document.getElementById('view-menu-button'));
 add('rfi','RFI',[{label:'วาด Revision Cloud',run:()=>{document.querySelector('[data-workspace-view="canvas"]').click();document.getElementById('rfi-cloud').click();}},{target:'rfi-open',label:'เปิดแผง RFI'},{target:'rfi-register-open',label:'ทะเบียน RFI'}]);
 const help=document.createElement('a');help.href='./guide.html#blend-guide';help.target='_blank';help.rel='noopener';help.textContent='คู่มือ';help.style.padding='6px 10px';nav.append(help);
 document.getElementById('view-menu-button').addEventListener('click',closeAll);document.getElementById('view-menu-button').addEventListener('keydown',closeAll);
 document.addEventListener('pointerdown',e=>{if(!e.target.closest('.app-menu'))closeAll();});document.addEventListener('focusin',e=>{if(!e.target.closest('.app-menu'))closeAll();});
}
