export function installDrawingBar({engine,getProject}){
 const viewport=document.getElementById('canvas-viewport');const bar=document.createElement('div');bar.id='drawing-tool-bar';bar.setAttribute('role','toolbar');bar.setAttribute('aria-label','เครื่องมือเขียนแบบ');
 const tools=document.createElement('div');tools.id='drawing-tool-items';bar.append(tools);
 const move=(id,icon,label)=>{const b=document.getElementById(id);if(!b)return;const title=b.title||label;b.replaceChildren();const glyph=document.createElement('span');glyph.textContent=icon;glyph.setAttribute('aria-hidden','true');const text=document.createElement('span');text.textContent=label;b.append(glyph,text);b.title=title;b.setAttribute('aria-label',label);tools.append(b);return b;};
 move('annotation-select','↖','เลือก');move('pan-toggle','✋','เลื่อน');
 const shortcut=(mode,icon,label)=>{const b=document.createElement('button');b.type='button';b.dataset.measureShortcut=mode;b.textContent=icon+' '+label;b.onclick=()=>{const panel=document.querySelector('.measure-panel');if(panel.hidden)document.getElementById('measure-tools').click();panel.querySelector('[data-mode="'+mode+'"]').click();};tools.append(b);};
 shortcut('scale','↔','ตั้งมาตราส่วน');const units=document.createElement('select');units.setAttribute('aria-label','หน่วย Dimension ทั้งแผ่น');for(const value of ['mm','m'])units.add(new Option(value,value));units.title='เปลี่ยนหน่วย Dimension เดิมและใหม่บนแผ่นที่เลือก';units.onchange=()=>{const target=document.querySelector('.display-unit');target.value=units.value;target.dispatchEvent(new Event('change'));};tools.append(units);shortcut('distance','↔','วัดระยะ');shortcut('arrow','↗','ลูกศรข้อความ');move('rfi-cloud','☁','Cloud');move('revision-diff-open','◩','ตรวจจุดต่าง');move('measure-tools','⚙','ตั้งค่าการวัด');move('export-overlay','⇩','Export PDF');
 const fold=document.createElement('button');fold.id='drawing-tools-fold';fold.setAttribute('aria-controls',tools.id);fold.setAttribute('aria-expanded','true');fold.textContent='▾';fold.title='พับแถบเครื่องมือ';fold.onclick=()=>{tools.hidden=!tools.hidden;fold.textContent=tools.hidden?'▴ เครื่องมือ':'▾';fold.setAttribute('aria-expanded',String(!tools.hidden));};bar.append(fold);viewport.append(bar);
 const sync=()=>{const p=getProject();units.value=p?.layers.find(l=>l.id===p.selectedId)?.dimensionUnit||'mm';const active=engine.tools?.active;document.getElementById('annotation-select')?.setAttribute('aria-pressed',String(active==='measure'&&engine.measureMode==='select'));for(const b of tools.querySelectorAll('[data-measure-shortcut]'))b.setAttribute('aria-pressed',String(active==='measure'&&b.dataset.measureShortcut===engine.measureMode));};
 bar.addEventListener('click',()=>queueMicrotask(sync));window.addEventListener('drawing-tool-change',sync);sync();
}
