import {TitleBlockReader} from "./title-block-reader.mjs";
import {inverse,map} from './model.mjs';
export function gridBounds(layer,rect){
 const lines=layer?.gridLines||[],points=[{x:rect.x,y:rect.y},{x:rect.x+rect.w,y:rect.y},{x:rect.x,y:rect.y+rect.h},{x:rect.x+rect.w,y:rect.y+rect.h}].map(p=>map(inverse(layer.transform),p));
 const ranges=[];
 for(const axis of ['letters','numbers']){
  const group=lines.filter(l=>l.axis===axis);if(group.length<2)return null;
  const first=group[0],dx=first.b.x-first.a.x,dy=first.b.y-first.a.y,len=Math.hypot(dx,dy),sign=(Math.abs(dy)>=Math.abs(dx)?-dy:dx)<0?-1:1,nx=-dy/len*sign,ny=dx/len*sign;
  if(!len)return null;
  if(group.some(l=>{const x=l.b.x-l.a.x,y=l.b.y-l.a.y;return Math.abs((x*nx+y*ny)/Math.hypot(x,y))>.02;}))return null;
  const sorted=group.map(l=>({name:l.name,v:l.a.x*nx+l.a.y*ny})).sort((a,b)=>a.v-b.v),values=points.map(p=>p.x*nx+p.y*ny),lo=Math.min(...values),hi=Math.max(...values),tol=.5;
  const a=sorted.filter(l=>l.v<=lo+tol).at(-1),b=sorted.find(l=>l.v>=hi-tol);if(!a||!b)return null;
  ranges.push(a.name===b.name?a.name:a.name+'-'+b.name);
 }
 return 'Gl.'+ranges.join('/');
}
export function editGrid(layer,source,onSave){
 if(!source)return;
 const dialog=document.createElement('dialog');dialog.className='grid-editor';dialog.innerHTML='<h2>กำหนด Grid line</h2><p>เลือกแถบบนแล้วครอบหัวกริดพร้อมระยะตลอดแนว จากนั้นเลือกแถบซ้ายแล้วครอบตลอดแนว · ภาพจริงจะประกอบรอบภาพเมฆโดยไม่ใช้ OCR</p><select class="mode" aria-label="วิธีกำหนดกริด"><option value="bands">ครอบแถบภาพสำหรับ RFI</option><option value="crop">ลากครอบอ่านหัวกริด</option><option value="manual">คลิกสองจุดเอง</option></select><select class="direction" aria-label="ตำแหน่งแถบ"><option value="top">แถบบน/ล่าง → เส้นแนวตั้ง</option><option value="side">แถบซ้าย/ขวา → เส้นแนวนอน</option></select><select aria-label="แนวกริด"><option value="letters">แนวตัวอักษร A, B…</option><option value="numbers">แนวตัวเลข 1, 2…</option></select><input aria-label="ชื่อกริด" placeholder="ชื่อกริด เช่น A หรือ 1" maxlength="30"><button class="add">เพิ่มเส้น</button><span class="message"></span><canvas></canvas><div class="lines"></div><button class="cancel">ยกเลิก</button><button class="save">บันทึกกริด</button>';
 const q=s=>dialog.querySelector(s),canvas=q('canvas'),ctx=canvas.getContext('2d'),scale=Math.min(1000/source.width,620/source.height);canvas.width=Math.round(source.width*scale);canvas.height=Math.round(source.height*scale);let lines=structuredClone(layer.gridLines||[]),points=[],bands=structuredClone(layer.gridBands||{});
 function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(source,0,0,canvas.width,canvas.height);for(const l of [...lines,...(points.length===2?[{a:points[0],b:points[1],name:'…'}]:[])]){ctx.strokeStyle='#0284c7';ctx.lineWidth=2;ctx.beginPath();const dx=l.b.x-l.a.x,dy=l.b.y-l.a.y;ctx.moveTo((l.a.x-dx*100)*scale,(l.a.y-dy*100)*scale);ctx.lineTo((l.b.x+dx*100)*scale,(l.b.y+dy*100)*scale);ctx.stroke();ctx.font='bold 16px sans-serif';ctx.fillStyle='#dc2626';ctx.fillText(l.name,l.a.x*scale,l.a.y*scale);}for(const band of Object.values(bands)){ctx.strokeStyle='#f59e0b';ctx.lineWidth=2;ctx.strokeRect(band.x*scale,band.y*scale,band.w*scale,band.h*scale);}for(const p of points){ctx.fillStyle='red';ctx.fillRect(p.x*scale-4,p.y*scale-4,8,8);}}
 const controller=new AbortController(),reader=new TitleBlockReader(message=>q('.message').textContent=message);let cropping=null,reading=false;
 const position=e=>{const b=canvas.getBoundingClientRect();return {x:Math.max(0,Math.min(source.width,(e.clientX-b.left)*source.width/b.width)),y:Math.max(0,Math.min(source.height,(e.clientY-b.top)*source.height/b.height))};};
 canvas.onpointerdown=e=>{if(!['crop','bands'].includes(q('.mode').value)||reading||e.button!==0)return;cropping=position(e);canvas.setPointerCapture(e.pointerId);};
 canvas.onpointermove=e=>{if(!cropping)return;draw();const b=position(e);ctx.strokeStyle='#f59e0b';ctx.strokeRect(cropping.x*scale,cropping.y*scale,(b.x-cropping.x)*scale,(b.y-cropping.y)*scale);};
 canvas.onpointercancel=()=>{cropping=null;draw();};
 canvas.onpointerup=async e=>{if(!cropping)return;const a=cropping,b=position(e);cropping=null;const x=Math.min(a.x,b.x),y=Math.min(a.y,b.y),w=Math.abs(a.x-b.x),h=Math.abs(a.y-b.y);if(w*scale<8||h*scale<8)return;
 if(q('.mode').value==='bands'){const direction=w>h*2?'top':h>w*2?'side':q('.direction').value;bands[direction]={x,y,w,h};q('.direction').value=direction==='top'?'side':'top';q('.message').textContent='แถบบน: '+(bands.top?'พร้อม':'ยังไม่เลือก')+' · แถบซ้าย: '+(bands.side?'พร้อม':'ยังไม่เลือก');draw();return;}
 const axis=q('select[aria-label="แนวกริด"]').value,vertical=q('.direction').value==='top';reading=true;q('.save').disabled=true;
 try{const crop=document.createElement('canvas'),factor=Math.min(3,2200/Math.max(w,h));crop.width=Math.ceil(w*factor);crop.height=Math.ceil(h*factor);crop.getContext('2d').drawImage(source,x,y,w,h,0,0,crop.width,crop.height);let words=await reader.ocr(crop,controller.signal,true,true);if(words.length<2)words=await reader.ocr(crop,controller.signal,true,false);if(controller.signal.aborted)return;let count=0;
 for(const word of words){const name=word.text.trim().toUpperCase();if(!/^[A-Z0-9]{1,4}(?:[.-][A-Z0-9]{1,3})?$/.test(name))continue;const px=x+(word.x+word.w/2)*w,py=y+(word.y+word.h/2)*h;if(lines.some(l=>l.axis===axis&&l.name===name))continue;lines.push({name,axis,a:vertical?{x:px,y:0}:{x:0,y:py},b:vertical?{x:px,y:source.height}:{x:source.width,y:py}});count++;}
 q('.message').textContent=count?'เสนอ '+count+' เส้น · ตรวจชื่อและตำแหน่งก่อนบันทึก':'อ่านไม่พบ ลองครอบเฉพาะหัวกริดให้แคบลง หรือใช้คลิกสองจุด';list();draw();}catch(e){if(!controller.signal.aborted)q('.message').textContent=e.message;}finally{reading=false;q('.save').disabled=false;}};
 function list(){q('.lines').replaceChildren();lines.forEach((l,i)=>{const row=document.createElement('div'),input=document.createElement('input'),pos=document.createElement('input'),del=document.createElement('button');input.value=l.name;input.setAttribute('aria-label','แก้ชื่อกริด');input.maxLength=30;input.onchange=()=>{l.name=input.value.trim();draw();};const vertical=Math.abs(l.b.y-l.a.y)>Math.abs(l.b.x-l.a.x);pos.type='number';pos.step='1';pos.value=vertical?l.a.x:l.a.y;pos.setAttribute('aria-label','ตำแหน่งกริด');pos.onchange=()=>{const value=Number(pos.value);if(!Number.isFinite(value))return;const key=vertical?'x':'y',delta=value-l.a[key];l.a[key]+=delta;l.b[key]+=delta;draw();};del.textContent='ลบ';del.onclick=()=>{lines.splice(i,1);list();draw();};row.append(input,pos,del);q('.lines').append(row);});}

 canvas.onclick=e=>{if(q('.mode').value!=='manual')return;const r=canvas.getBoundingClientRect();if(points.length===2)points=[];points.push({x:(e.clientX-r.left)*source.width/r.width,y:(e.clientY-r.top)*source.height/r.height});draw();};
 q('.add').onclick=()=>{const name=q('input').value.trim(),axis=q('select[aria-label="แนวกริด"]').value;if(!name||points.length!==2||Math.hypot(points[1].x-points[0].x,points[1].y-points[0].y)*scale<15){q('.message').textContent='ใส่ชื่อและเลือกสองจุดให้ห่างกัน';return;}if(lines.some(l=>l.axis===axis&&l.name===name)){q('.message').textContent='ชื่อนี้มีแล้ว ลบเส้นเดิมก่อนแก้';return;}lines.push({name,axis,a:points[0],b:points[1]});points=[];q('input').value='';q('.message').textContent='เพิ่มแล้ว';list();draw();};
 q('.save').onclick=async()=>{if(reading)return;if(q('.mode').value==='bands'&&(!bands.top||!bands.side)){q('.message').textContent='เลือกแถบบนและแถบซ้ายให้ครบก่อนบันทึก';return;}if(lines.some(l=>!l.name)||new Set(lines.map(l=>l.axis+':'+l.name)).size!==lines.length){q('.message').textContent='ชื่อกริดว่างหรือซ้ำ กรุณาแก้ก่อนบันทึก';return;}if(points.length){q('.message').textContent='กดเพิ่มเส้นก่อนบันทึก';return;}q('.save').disabled=true;try{await onSave(lines,bands);dialog.close();}catch(e){q('.message').textContent=e.message;}finally{q('.save').disabled=false;}};q('.cancel').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{controller.abort();reader.stop();dialog.remove();});document.body.append(dialog);dialog.showModal();draw();list();const modeUI=()=>{const bandMode=q('.mode').value==='bands';q('select[aria-label="แนวกริด"]').hidden=bandMode;q('input[aria-label="ชื่อกริด"]').hidden=bandMode;q('.add').hidden=q('.mode').value!=='manual';q('.lines').hidden=bandMode;points=[];draw();};q('.mode').onchange=modeUI;modeUI();
}
