import {pdfSnapPoints,nearestSnap} from './pdf-snap.mjs';
import {inverse,map} from './model.mjs';
export function orthogonalPoint(start,end,axis='auto'){
 if(axis==='free')return end;
 const horizontal=axis==='horizontal'||(axis==='auto'&&Math.abs(end.x-start.x)>=Math.abs(end.y-start.y));
 return horizontal?{x:end.x,y:start.y}:{x:start.x,y:end.y};
}
export const measuredDistance=(a,b,scale)=>Math.hypot(b.x-a.x,b.y-a.y)*scale;
export function drawMeasures(engine,ctx,region={x:0,y:0},density=1){
 const p=engine.p,l=p?.layers.find(l=>l.id===p.selectedId);if(!l||!l.visible)return;const cam=p.camera;
 const point=a=>{const w=map(l.transform,a);return {x:(w.x*cam.zoom+cam.x-region.x)*density,y:(w.y*cam.zoom+cam.y-region.y)*density};};

 for(const m of l.measurements||[]){const a=point(m.a),b=point(m.b),angle=Math.atan2(b.y-a.y,b.x-a.x);ctx.save();ctx.strokeStyle=ctx.fillStyle='#0369a1';ctx.lineWidth=2*density;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();
 const arrow=(p,t)=>{ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x+12*density*Math.cos(t-.4),p.y+12*density*Math.sin(t-.4));ctx.lineTo(p.x+12*density*Math.cos(t+.4),p.y+12*density*Math.sin(t+.4));ctx.closePath();ctx.fill();};arrow(a,angle);if(m.kind==='distance')arrow(b,angle+Math.PI);
 const unit=(l.dimensionUnit||m.unit)==='m'?'m':'mm',value=l.measureScale?measuredDistance(m.a,m.b,l.measureScale.mmPerPixel)/(unit==='m'?1000:1):null;
 const label=m.kind==='distance'?(value!==null?value.toLocaleString('en-US',{maximumFractionDigits:unit==='m'?3:1})+' '+unit:'ยังไม่ตั้งมาตราส่วน'):m.text;
 ctx.font=14*density+'px Tahoma';const width=ctx.measureText(label).width,tx=m.kind==='distance'?(a.x+b.x-width)/2:b.x,ty=m.kind==='distance'?(a.y+b.y)/2-13*density:b.y;
 ctx.fillStyle='white';ctx.fillRect(tx-3*density,ty-10*density,width+6*density,20*density);ctx.fillStyle='#0369a1';ctx.textBaseline='middle';ctx.fillText(label,tx,ty);ctx.restore();}

}
export function installMeasurements({engine,getProject,mutate,toast,getSource}){
 const button=document.createElement('button');button.textContent='วัด / ลูกศร';button.id='measure-tools';document.getElementById('rfi-open').after(button);
 const panel=document.createElement('div');panel.className='measure-panel';panel.hidden=true;panel.innerHTML='<strong>เครื่องมือวัด · แผ่นที่เลือก</strong><p class="scale-state"></p><label><input type="checkbox" class="vector-snap"> สแนปจุดเวกเตอร์ PDF</label><p class="snap-status" role="status"></p><label>ระยะอ้างอิง <input class="known" type="number" min="0.001" step="any" value="6000"></label><select class="unit" aria-label="หน่วยระยะอ้างอิง"><option value="1">mm</option><option value="10">cm</option><option value="1000">m</option></select><button data-mode="scale">ตั้งมาตราส่วน</button><button data-mode="distance">วัดระยะ</button><label>แนววัดบนหน้าจอ<select class="measure-axis" aria-label="แนววัด"><option value="auto">ล็อกฉากอัตโนมัติ</option><option value="horizontal">แนวนอน</option><option value="vertical">แนวตั้ง</option><option value="free">อิสระ</option></select></label><input class="arrow-text" maxlength="200" placeholder="ข้อความกำกับลูกศร" aria-label="ข้อความลูกศร"><button data-mode="arrow">ลูกศรข้อความ</button><button data-mode="select">เลือก / แก้ไข</button><label>หน่วยแสดงผล<select class="display-unit" aria-label="หน่วยแสดงผล"><option>mm</option><option>m</option></select></label><button class="edit-text">บันทึกข้อความที่เลือก</button><button class="remove">ลบที่เลือก</button><button class="close">ปิด</button><p class="hint">ตั้งมาตราส่วนและวัดระยะใช้แนวหน้าจอที่เลือก · Shift ล็อกฉากชั่วคราวในโหมดอิสระ · ลูกศรชี้จุดเริ่มลาก · Esc ยกเลิก · Undo ย้อนกลับได้</p>';
 document.body.append(panel);let mode=null,drag=null,picked=null,editDrag=null,marquee=null;const pickedIds=new Set();
 let snapData=null,snapKey=null,snapMark=null,request=0;
 const snapToggle=panel.querySelector('.vector-snap'),snapStatus=panel.querySelector('.snap-status');
 const key=l=>l?[getProject()?.id,l.id,l.sourceId,l.page,l.width,l.height].join(':'):null;
 snapToggle.onchange=async()=>{const id=++request;snapData=null;snapMark=null;if(!snapToggle.checked){snapStatus.textContent='ปิดสแนป';return;}const l=selected(),sourceKey=key(l);if(!l)return;snapStatus.textContent='กำลังอ่านเวกเตอร์ PDF…';try{const blob=await getSource?.(l);if(!blob)throw Error('ไม่พบ PDF ต้นฉบับ');const points=await pdfSnapPoints(blob,l);if(id!==request||sourceKey!==key(selected()))return;snapData=points;snapKey=sourceKey;snapStatus.textContent=points.length?'พร้อมสแนป '+points.length.toLocaleString()+' จุด · ปลายเส้น/มุม':'ไม่พบเวกเตอร์ · เลือกจุดด้วยมือ';}catch(e){if(id===request)snapStatus.textContent='อ่านเวกเตอร์ไม่ได้ · เลือกจุดด้วยมือ';}};
 const snap=(q)=>{snapMark=null;if(snapToggle.checked&&snapData&&snapKey===key(selected()))snapMark=nearestSnap(snapData,selected(),getProject().camera,q);return snapMark||q;};
 const selected=()=>getProject()?.layers.find(l=>l.id===getProject().selectedId);
 const stop=()=>{mode=null;marquee=null;pickedIds.clear();engine.measureMode=null;drag=null;editDrag=null;engine.cursor();engine.render();};
 let heldPointer=null;engine.canvas.addEventListener('gotpointercapture',e=>{heldPointer=e.pointerId;});engine.canvas.addEventListener('lostpointercapture',()=>{heldPointer=null;});engine.tools?.register('measure',()=>{picked=null;snapMark=null;stop();if(heldPointer!==null&&engine.canvas.hasPointerCapture(heldPointer))engine.canvas.releasePointerCapture(heldPointer);heldPointer=null;});
 const refresh=()=>{const l=selected();panel.querySelector('.display-unit').value=l?.dimensionUnit||'mm';if(snapKey&&snapKey!==key(l)){snapData=null;snapMark=null;snapToggle.checked=false;snapStatus.textContent='เปลี่ยนแผ่นแล้ว · เปิดสแนปเพื่ออ่าน PDF ของแผ่นนี้';}panel.querySelector('.scale-state').textContent=l?l.name+' · '+(l.measureScale?'ตั้งมาตราส่วนแล้ว':'ยังไม่ตั้งมาตราส่วน'): 'เลือกแผ่นแบบก่อน';};
 button.onclick=()=>{panel.hidden=!panel.hidden;stop();refresh();};panel.querySelector('.close').onclick=()=>{panel.hidden=true;stop();};
 for(const b of panel.querySelectorAll('[data-mode]'))b.onclick=()=>{if(['scale','distance','arrow'].includes(b.dataset.mode)&&mode===b.dataset.mode){if(engine.tools)engine.tools.reset();else stop();panel.hidden=true;window.dispatchEvent(new Event('drawing-tool-change'));return;}const l=selected(),p=getProject();if(!l||l.locked||!l.visible||p.calibration){toast('เลือกแผ่นที่แสดงและปลดล็อกก่อน',true);return;}if(b.dataset.mode==='distance'&&!l.measureScale){toast('ตั้งมาตราส่วนจากระยะที่ทราบก่อนวัด',true);return;}if(document.getElementById('rfi-cloud').getAttribute('aria-pressed')==='true')document.getElementById('rfi-cloud').click();engine.tools?.activate('measure');p.panMode=false;mode=b.dataset.mode;engine.measureMode=mode;engine.canvas.style.cursor='crosshair';toast('ลากจุดแรกไปจุดที่สองบนแผ่นแบบ');};
 const selectButton=document.createElement('button');selectButton.id='annotation-select';selectButton.textContent='เลือก';button.before(selectButton);selectButton.onclick=()=>{const p=getProject();if(!p||p.calibration)return;p.panMode=false;panel.querySelector('[data-mode="select"]').click();};
 const chosen=()=>{const l=selected();if(!l?.visible){picked=null;return null;}return l.measurements?.find(m=>m.id===picked);};
 const displayUnit=panel.querySelector('.display-unit');displayUnit.parentElement.style.display='contents';panel.querySelector('[data-mode="scale"]').after(displayUnit);displayUnit.title='หน่วย Dimension ทั้งแผ่นที่เลือก';
 displayUnit.onchange=async()=>{const l=selected();if(!l||l.locked||getProject().calibration)return;try{await mutate('เปลี่ยนหน่วย Dimension ทั้งแผ่นแล้ว',()=>{l.dimensionUnit=displayUnit.value;for(const m of l.measurements||[])if(m.kind==='distance')m.unit=displayUnit.value;});}catch(e){toast(e.message,true);}};
 panel.querySelector('.edit-text').onclick=async()=>{const m=chosen(),l=selected();if(m?.kind==='arrow'&&!l.locked&&!getProject().calibration)try{await mutate('แก้ข้อความแล้ว',()=>m.text=panel.querySelector('.arrow-text').value.trim());}catch(e){toast(e.message,true);}};
 panel.querySelector('.remove').onclick=async()=>{const l=selected();if(!l||!l.visible||l.locked||getProject()?.calibration)return;try{if(!chosen()&&!pickedIds.size)return toast('คลิกเลือกรายการก่อนลบ',true);await mutate('ลบรายการที่เลือกแล้ว',()=>l.measurements=l.measurements.filter(m=>m.id!==picked&&!pickedIds.has(m.id)));picked=null;pickedIds.clear();}catch(e){toast(e.message,true);}};
 document.getElementById('rfi-cloud').addEventListener('click',stop);window.addEventListener('keydown',e=>{if(e.key==='Escape'){picked=null;engine.clearCloudSelection?.();stop();}if(e.key==='Delete'&&!e.repeat&&!e.target.closest?.('input,textarea,select,[contenteditable="true"],[role="textbox"]')&&!document.querySelector('dialog[open]')&&!getProject()?.calibration&&!drag&&!editDrag){if(chosen()||pickedIds.size){e.preventDefault();panel.querySelector('.remove').click();}else if(engine.deleteSelectedCloud?.()){e.preventDefault();engine.render();}}});
 const canvas=engine.canvas;
 canvas.addEventListener('dblclick',()=>{if(chosen()){panel.hidden=false;refresh();}});

 const screenPoint=(l,a)=>{const w=map(l.transform,a),c=getProject().camera;return {x:w.x*c.zoom+c.x,y:w.y*c.zoom+c.y};};
 canvas.addEventListener('pointerdown',e=>{if((mode&&mode!=='select')||e.button!==0||getProject()?.panMode||document.getElementById('rfi-cloud').getAttribute('aria-pressed')==='true')return;const l=selected();if(getProject()?.calibration){mode=null;return;}if(!l||l.locked||!l.visible)return stop();const q=engine.screen(e);let found=null;
 for(const m of [...(l.measurements||[])].reverse()){const a=screenPoint(l,m.a),b=screenPoint(l,m.b),dx=b.x-a.x,dy=b.y-a.y,t=Math.max(0,Math.min(1,((q.x-a.x)*dx+(q.y-a.y)*dy)/(dx*dx+dy*dy||1)));if(Math.hypot(q.x-a.x-t*dx,q.y-a.y-t*dy)<18){found=m;break;}}
 pickedIds.clear();picked=found?.id||null;engine.clearCloudSelection?.();const cloudHit=!found&&engine.selectCloud?.(q);if(!found&&!cloudHit&&mode==='select'){marquee={start:q,end:q,p:getProject(),l};canvas.setPointerCapture(e.pointerId);e.preventDefault();e.stopImmediatePropagation();canvas.tabIndex=0;canvas.focus();}if(found||cloudHit){e.preventDefault();e.stopImmediatePropagation();canvas.tabIndex=0;canvas.focus({preventScroll:true});}if(found){panel.querySelector('.display-unit').value=l.dimensionUnit||found.unit||'mm';panel.querySelector('.arrow-text').value=found.text||'';for(const key of ['a','b'])if(mode==='select'&&Math.hypot(q.x-screenPoint(l,found[key]).x,q.y-screenPoint(l,found[key]).y)<14){editDrag={p:getProject(),l,id:found.id,key,end:q};canvas.setPointerCapture(e.pointerId);break;}if(mode==='select'&&!editDrag){editDrag={p:getProject(),l,id:found.id,key:'move',start:q,end:q};canvas.setPointerCapture(e.pointerId);}}engine.render();},true);
 canvas.addEventListener('pointermove',e=>{if(marquee){e.preventDefault();e.stopImmediatePropagation();marquee.end=engine.screen(e);engine.render();return;}if(!editDrag)return;e.preventDefault();e.stopImmediatePropagation();editDrag.end=engine.screen(e);engine.render();},true);
 canvas.addEventListener('pointerup',async e=>{if(marquee){e.preventDefault();e.stopImmediatePropagation();const box=marquee;marquee=null;if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);if(box.p!==getProject()||box.l!==selected())return;const end=engine.screen(e),left=Math.min(box.start.x,end.x),right=Math.max(box.start.x,end.x),top=Math.min(box.start.y,end.y),bottom=Math.max(box.start.y,end.y);for(const m of box.l.measurements||[]){const a=screenPoint(box.l,m.a),b=screenPoint(box.l,m.b);if([a,b].every(q=>q.x>=left&&q.x<=right&&q.y>=top&&q.y<=bottom))pickedIds.add(m.id);}picked=pickedIds.values().next().value||null;toast('เลือก '+pickedIds.size+' รายการ · Delete ลบ · Esc ยกเลิก');engine.render();return;}if(!editDrag)return;e.preventDefault();e.stopImmediatePropagation();const d=editDrag;editDrag=null;if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);if(d.p!==getProject()||d.l!==selected()||d.l.locked||getProject().calibration)return;const m=chosen();if(!m||m.id!==d.id)return;if(d.key==='move'){const end=engine.screen(e);if(Math.hypot(end.x-d.start.x,end.y-d.start.y)<3)return;const inv=inverse(d.l.transform),start=map(inv,engine.world(d.start)),finish=map(inv,engine.world(end));try{await mutate('ย้ายเส้นแล้ว',()=>{for(const key of ['a','b'])m[key]={x:m[key].x+finish.x-start.x,y:m[key].y+finish.y-start.y};});}catch(err){toast(err.message,true);}engine.render();return;}const other=screenPoint(d.l,m[d.key==='a'?'b':'a']),q=m.kind==='distance'?orthogonalPoint(other,engine.screen(e),panel.querySelector('.measure-axis').value):engine.screen(e);if(Math.hypot(q.x-other.x,q.y-other.y)<8)return;try{await mutate('แก้ปลายเส้นแล้ว',()=>m[d.key]=map(inverse(d.l.transform),engine.world(q)));}catch(err){toast(err.message,true);}engine.render();},true);
 const endPoint=(d,e)=>{const q=engine.screen(e),axis=e.shiftKey&&d.axis==='free'?'auto':d.axis,locked=(d.mode==='distance'||d.mode==='scale')&&axis!=='free',base=locked?orthogonalPoint(d.start,q,axis):q,candidate=snap(base);if(locked){const projected=orthogonalPoint(d.start,candidate,axis);if(Math.hypot(projected.x-candidate.x,projected.y-candidate.y)>.1){snapMark=null;return base;}}return candidate;};
 canvas.addEventListener('pointerdown',e=>{if(!mode||mode==='select'||e.button!==0)return;const p=getProject(),l=selected();if(!l||l.locked||p.calibration)return stop();e.preventDefault();e.stopImmediatePropagation();drag={p,l,mode,axis:panel.querySelector(".measure-axis").value,start:snap(engine.screen(e)),end:engine.screen(e)};canvas.setPointerCapture(e.pointerId);},true);
 canvas.addEventListener('pointermove',e=>{if(getProject()?.calibration){mode=null;drag=null;editDrag=null;snapMark=null;return;}if(!drag){if(mode&&mode!=='select'){snap(engine.screen(e));engine.render();}return;}e.preventDefault();e.stopImmediatePropagation();drag.end=endPoint(drag,e);engine.render();},true);
 canvas.addEventListener('pointerup',async e=>{if(!drag)return;e.preventDefault();e.stopImmediatePropagation();const d=drag;d.end=endPoint(d,e);if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);stop();if(d.p!==getProject()||d.l!==selected()||d.l.locked||getProject().calibration||Math.hypot(d.end.x-d.start.x,d.end.y-d.start.y)<8)return;const inv=inverse(d.l.transform),a=map(inv,engine.world(d.start)),b=map(inv,engine.world(d.end));try{if(d.mode==='scale'){const mm=Number(panel.querySelector('.known').value)*Number(panel.querySelector('.unit').value);if(!Number.isFinite(mm)||mm<=0)throw Error('กรอกระยะอ้างอิงมากกว่า 0');await mutate('ตั้งมาตราส่วนแล้ว',()=>d.l.measureScale={mmPerPixel:mm/Math.hypot(b.x-a.x,b.y-a.y),referenceMm:mm,a,b});}else{const text=panel.querySelector('.arrow-text').value.trim();if(d.mode==='arrow'&&!text)throw Error('กรอกข้อความลูกศรก่อน');await mutate('เพิ่มรายการวัดแล้ว',()=>{(d.l.measurements??=[]).push({id:(picked=crypto.randomUUID()),kind:d.mode,a,b,text,unit:panel.querySelector('.display-unit').value});});}refresh();}catch(e){toast(e.message,true);}},true);
 canvas.addEventListener('pointercancel',stop);canvas.addEventListener('wheel',()=>{if(drag)stop();},true);
 const prior=engine.drawMarkup;engine.drawMarkup=()=>{prior?.();if(getProject()?.calibration)return;const ctx=engine.ctx;ctx.save();ctx.setTransform(engine.dpr,0,0,engine.dpr,0,0);drawMeasures(engine,ctx);if(marquee){const a=marquee.start,b=marquee.end;ctx.fillStyle='rgba(250,204,21,.12)';ctx.strokeStyle='#eab308';ctx.setLineDash([5,4]);ctx.fillRect(Math.min(a.x,b.x),Math.min(a.y,b.y),Math.abs(b.x-a.x),Math.abs(b.y-a.y));ctx.strokeRect(Math.min(a.x,b.x),Math.min(a.y,b.y),Math.abs(b.x-a.x),Math.abs(b.y-a.y));ctx.setLineDash([]);}for(const m of selected()?.measurements||[]){if(pickedIds.has(m.id)){ctx.fillStyle='#f59e0b';for(const key of ['a','b']){const q=screenPoint(selected(),m[key]);ctx.fillRect(q.x-5,q.y-5,10,10);}}}if(snapMark&&mode&&snapKey===key(selected())){ctx.strokeStyle="#16a34a";ctx.lineWidth=2;ctx.strokeRect(snapMark.x-5,snapMark.y-5,10,10);}const active=chosen(),l=selected();if(active&&l.visible){ctx.fillStyle='#f59e0b';for(const key of ['a','b']){const q=screenPoint(l,active[key]);ctx.fillRect(q.x-5,q.y-5,10,10);}if(editDrag&&editDrag.key!=='move'){const other=screenPoint(l,active[editDrag.key==='a'?'b':'a']);const q=active.kind==='distance'?orthogonalPoint(other,editDrag.end,panel.querySelector('.measure-axis').value):editDrag.end;ctx.strokeStyle='#f59e0b';ctx.beginPath();ctx.moveTo(other.x,other.y);ctx.lineTo(q.x,q.y);ctx.stroke();}}if(drag){ctx.strokeStyle='#0369a1';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(drag.start.x,drag.start.y);ctx.lineTo(drag.end.x,drag.end.y);ctx.stroke();}ctx.restore();};
}

