export function differencePixels(oldData,newData,threshold=35){
 const out=new Uint8ClampedArray(oldData.length);let added=0,removed=0;
 for(let i=0;i<out.length;i+=4){const gray=d=>(d[i]*.2126+d[i+1]*.7152+d[i+2]*.0722)*(d[i+3]/255)+255*(1-d[i+3]/255);const delta=gray(oldData)-gray(newData);const add=delta>threshold,remove=delta < -threshold;
 if(add||remove){out[i]=add?230:0;out[i+1]=add?30:115;out[i+2]=add?40:230;out[i+3]=210;if(add)added++;else removed++;}}
 return {data:out,added,removed};
}
export function installRevisionDiff({engine,getProject,toast}){
 const button=document.createElement('button');button.textContent='ตรวจจุดต่าง';document.getElementById('rfi-cloud').before(button);
 let armed=false,start=null,project=null,pointerId=null;
 const selection=document.createElement('div');selection.className='diff-selection';selection.hidden=true;selection.setAttribute('aria-hidden','true');selection.style.cssText='position:absolute;pointer-events:none;z-index:20;border:2px dashed #eab308;background:rgba(250,204,21,.12);box-sizing:border-box';engine.canvas.parentElement.append(selection);
 const point=e=>{const q=engine.screen(e);return {x:Math.max(0,Math.min(engine.width,q.x)),y:Math.max(0,Math.min(engine.height,q.y))};};
 const paint=q=>{selection.hidden=false;Object.assign(selection.style,{left:Math.min(start.x,q.x)/engine.width*100+'%',top:Math.min(start.y,q.y)/engine.height*100+'%',width:Math.abs(start.x-q.x)/engine.width*100+'%',height:Math.abs(start.y-q.y)/engine.height*100+'%'});};
 button.onclick=()=>{const p=getProject();if(!p||p.calibration||p.selectedId===p.baseId||!p.layers.find(l=>l.id===p.selectedId)?.alignment)return toast('เลือกแผ่นใหม่ที่ Calibrate กับฐานแล้วก่อนตรวจ',true);project=p;armed=!armed;button.setAttribute('aria-pressed',String(armed));engine.canvas.style.cursor=armed?'crosshair':'';toast('ฐาน = แบบเก่า · แผ่นที่เลือก = แบบใหม่ · ลากพื้นที่ตรวจบนแปลน');};
 const stop=()=>{armed=false;start=null;selection.hidden=true;if(pointerId!==null&&engine.canvas.hasPointerCapture(pointerId))engine.canvas.releasePointerCapture(pointerId);pointerId=null;engine.cursor();button.setAttribute('aria-pressed','false');};
 window.addEventListener('keydown',e=>{if(e.key==='Escape')stop();});
 window.addEventListener('pointerdown',e=>{if(!armed||e.target!==engine.canvas||e.button!==0)return;e.preventDefault();e.stopImmediatePropagation();start=point(e);pointerId=e.pointerId;engine.canvas.setPointerCapture(e.pointerId);paint(start);},true);
 window.addEventListener('pointermove',e=>{if(start&&e.pointerId===pointerId){e.preventDefault();e.stopImmediatePropagation();paint(point(e));}},true);
 window.addEventListener('pointerup',e=>{if(!start||e.pointerId!==pointerId)return;e.preventDefault();e.stopImmediatePropagation();const end=point(e),r={x:Math.min(start.x,end.x),y:Math.min(start.y,end.y),w:Math.abs(start.x-end.x),h:Math.abs(start.y-end.y)};stop();if(engine.canvas.hasPointerCapture(e.pointerId))engine.canvas.releasePointerCapture(e.pointerId);if(project!==getProject()||project.calibration||r.w<10||r.h<10)return;
 try{review(r);}catch(err){toast(err.message,true);}},true);
 window.addEventListener('pointercancel',stop);window.addEventListener('blur',stop);window.addEventListener('resize',stop);window.addEventListener('wheel',e=>{if(start){e.preventDefault();e.stopImmediatePropagation();}},{capture:true,passive:false});
 function review(r){const p=getProject(),old=p.layers.find(l=>l.id===p.baseId),fresh=p.layers.find(l=>l.id===p.selectedId);const scale=Math.min(2,1600/Math.max(r.w,r.h));const width=Math.max(1,Math.round(r.w*scale)),height=Math.max(1,Math.round(r.h*scale));
 const render=l=>{const source=engine.cache.get(l.assetId)?.source;if(!source)throw Error('ไม่พบภาพต้นฉบับ');const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.fillStyle='white';ctx.fillRect(0,0,width,height);const c=p.camera,t=l.transform;ctx.setTransform(c.zoom*scale,0,0,c.zoom*scale,(c.x-r.x)*scale,(c.y-r.y)*scale);ctx.transform(t.a,t.b,t.c,t.d,t.e,t.f);ctx.drawImage(source,0,0);ctx.resetTransform();return canvas;};
 const a=render(old),b=render(fresh),ad=a.getContext('2d').getImageData(0,0,width,height).data,bd=b.getContext('2d').getImageData(0,0,width,height).data;
 const dialog=document.createElement('dialog');dialog.style.cssText='width:min(1000px,94vw);max-height:90vh;overflow:auto';dialog.innerHTML='<h2>ตรวจจุดต่าง Revision</h2><p class="names"></p><p>แดง = เข้มขึ้น/อาจเพิ่ม · น้ำเงิน = จางลง/อาจลบ ไม่ใช่การยืนยันการเปลี่ยนแปลงทางวิศวกรรม</p><label>เกณฑ์ผลต่างสี (ต่ำ = ไวขึ้น) <input type="range" min="10" max="150" value="35"></label><select aria-label="ภาพตรวจ"><option value="diff">ผลต่างบนฐาน</option><option value="old">ต้นฉบับเก่า</option><option value="new">ต้นฉบับใหม่</option></select><p class="stats"></p><p>ความเหลื่อม ความหนาเส้นและคุณภาพสแกนทำให้เกิดจุดต่างได้ ตรวจต้นฉบับก่อนสร้าง RFI</p><button class="create">สร้าง RFI จากพื้นที่นี้</button><button class="close">ปิด</button>';
 dialog.querySelector('.names').textContent=old.name+' → '+fresh.name;const output=document.createElement('canvas');output.width=width;output.height=height;output.style.cssText='width:100%;height:auto;display:block;background:white';dialog.querySelector('.stats').after(output);
 const draw=()=>{const ctx=output.getContext('2d'),mode=dialog.querySelector('select').value;ctx.drawImage(mode==='new'?b:a,0,0);if(mode==='diff'){const result=differencePixels(ad,bd,Number(dialog.querySelector('input').value)),overlay=document.createElement('canvas');overlay.width=width;overlay.height=height;overlay.getContext('2d').putImageData(new ImageData(result.data,width,height),0,0);ctx.drawImage(overlay,0,0);dialog.querySelector('.stats').textContent='เกณฑ์ '+dialog.querySelector('input').value+' · จุดภาพแดง '+result.added+' / น้ำเงิน '+result.removed;}else dialog.querySelector('.stats').textContent='ภาพต้นฉบับในพื้นที่ตรวจ';};
 dialog.querySelector('input').onchange=draw;dialog.querySelector('select').onchange=draw;dialog.querySelector('.close').onclick=()=>dialog.close();dialog.querySelector('.create').onclick=async()=>{if(getProject()!==p||p.selectedId!==fresh.id)return;dialog.close();await engine.createRfiFromRect?.(r);};dialog.onclose=()=>dialog.remove();document.body.append(dialog);draw();dialog.showModal();
 }
}
